[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x2c2525"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16

